### ISSUE TITLE
Improve /help to include information read from a modifiable file

### ISSUE THREAD

**Issue by Avygeil** [Avygeil/base_enhanced#6]

**Comment by entdark** [comment]
base_enhanced is not about pugs :s
If it reads from some files server owners provided then ok.

**Comment by Avygeil** [comment]
yes, forgot to mention it has to read from a help file so server owners can edit info. Plus it would help not having to recompile every single time to change it.

**Comment by Avygeil** [comment]
448401192d33704823f26514ef0bc24bd6b3f352
